# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\" \n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"1\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0eMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0fMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"0\n\x0b\x43hatMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xf8\x01\n\x0b\x43hatService\x12\x30\n\x05Login\x12\x12.chat.LoginRequest\x1a\x13.chat.LoginResponse\x12\x35\n\x11GetRecentMessages\x12\x0b.chat.Empty\x1a\x11.chat.ChatMessage0\x01\x12\x45\n\x14SendMultipleMessages\x12\x14.chat.MessageRequest\x1a\x15.chat.MessageResponse(\x01\x12\x39\n\nChatStream\x12\x14.chat.MessageRequest\x1a\x11.chat.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=20
  _globals['_LOGINREQUEST']._serialized_end=52
  _globals['_LOGINRESPONSE']._serialized_start=54
  _globals['_LOGINRESPONSE']._serialized_end=103
  _globals['_MESSAGEREQUEST']._serialized_start=105
  _globals['_MESSAGEREQUEST']._serialized_end=156
  _globals['_MESSAGERESPONSE']._serialized_start=158
  _globals['_MESSAGERESPONSE']._serialized_end=191
  _globals['_CHATMESSAGE']._serialized_start=193
  _globals['_CHATMESSAGE']._serialized_end=241
  _globals['_EMPTY']._serialized_start=243
  _globals['_EMPTY']._serialized_end=250
  _globals['_CHATSERVICE']._serialized_start=253
  _globals['_CHATSERVICE']._serialized_end=501
# @@protoc_insertion_point(module_scope)
